local statusline = require("expedition.statusline")
local route = require("expedition.route")
local summit = require("expedition.summit")

describe("statusline", function()
  before_each(function()
    test_reset()
    statusline._reset()
    test_create_expedition("statusline-test")
    statusline.register()
  end)

  after_each(function()
    statusline._reset()
  end)

  describe("is_active", function()
    it("returns true when expedition is active", function()
      assert.is_true(statusline.is_active())
    end)

    it("returns false when no expedition is active", function()
      statusline._reset()
      test_clear_active()
      statusline.register()
      assert.is_false(statusline.is_active())
    end)
  end)

  describe("expedition", function()
    it("returns formatted expedition name and status", function()
      local result = statusline.expedition()
      assert.truthy(result:find("statusline%-test"))
      assert.truthy(result:find("%[active%]"))
    end)

    it("returns empty string when no expedition active", function()
      statusline._reset()
      test_clear_active()
      statusline.register()
      assert.equals("", statusline.expedition())
    end)
  end)

  describe("branch", function()
    it("returns current branch", function()
      local result = statusline.branch()
      assert.truthy(result:find("main"))
    end)

    it("returns empty string when no expedition active", function()
      statusline._reset()
      test_clear_active()
      statusline.register()
      assert.equals("", statusline.branch())
    end)
  end)

  describe("progress", function()
    it("returns empty string when no waypoints", function()
      assert.equals("", statusline.progress())
    end)

    it("returns done/total format", function()
      route.create_waypoint({ title = "WP1" })
      route.create_waypoint({ title = "WP2" })
      statusline.invalidate()

      local result = statusline.progress()
      assert.equals("Route: 0/2", result)
    end)

    it("counts done waypoints", function()
      local wp1 = route.create_waypoint({ title = "WP1" })
      route.create_waypoint({ title = "WP2" })
      route.set_status(wp1.id, "done")
      statusline.invalidate()

      local result = statusline.progress()
      assert.equals("Route: 1/2", result)
    end)
  end)

  describe("active_waypoint", function()
    it("returns empty string when no active waypoint", function()
      route.create_waypoint({ title = "WP1" })
      statusline.invalidate()
      assert.equals("", statusline.active_waypoint())
    end)

    it("returns active waypoint title", function()
      local wp = route.create_waypoint({ title = "Implement OAuth" })
      route.set_status(wp.id, "active")
      statusline.invalidate()

      local result = statusline.active_waypoint()
      assert.truthy(result:find("Implement OAuth"))
    end)
  end)

  describe("conditions", function()
    it("returns empty string when no conditions", function()
      assert.equals("", statusline.conditions())
    end)

    it("returns met/total format", function()
      summit.create("Condition 1")
      summit.create("Condition 2")
      statusline.invalidate()

      local result = statusline.conditions()
      assert.equals("Summit: 0/2", result)
    end)

    it("counts met conditions", function()
      local c1 = summit.create("Condition 1")
      summit.create("Condition 2")
      summit.set_status(c1.id, "met")
      statusline.invalidate()

      local result = statusline.conditions()
      assert.equals("Summit: 1/2", result)
    end)
  end)

  describe("drift", function()
    it("returns empty string when no drifted notes", function()
      assert.equals("", statusline.drift())
    end)

    it("returns empty string when no expedition active", function()
      statusline._reset()
      test_clear_active()
      statusline.register()
      assert.equals("", statusline.drift())
    end)
  end)

  describe("cache invalidation", function()
    it("invalidates on hook events", function()
      -- Initial read
      local result1 = statusline.progress()
      assert.equals("", result1)

      -- Create a waypoint (dispatches hook which sets _dirty)
      route.create_waypoint({ title = "New WP" })

      -- Should reflect new data
      local result2 = statusline.progress()
      assert.equals("Route: 0/1", result2)
    end)
  end)

  describe("lualine", function()
    it("returns a table with function, cond, and color", function()
      local component = statusline.lualine()
      assert.is_function(component[1])
      assert.equals(statusline.is_active, component.cond)
      assert.is_table(component.color)
    end)

    it("renders combined statusline text", function()
      local wp = route.create_waypoint({ title = "My Task" })
      route.set_status(wp.id, "active")
      statusline.invalidate()

      local component = statusline.lualine()
      local text = component[1]()
      assert.truthy(text:find("statusline%-test"))
      assert.truthy(text:find("Route:"))
      assert.truthy(text:find("My Task"))
    end)
  end)
end)
