local summit = require("expedition.summit")
local hooks = require("expedition.hooks")

describe("summit", function()
  before_each(function()
    test_reset()
    test_create_expedition("summit-test")
  end)

  describe("conditions_path", function()
    it("returns path when expedition is active", function()
      local path = summit.conditions_path()
      assert.is_string(path)
      assert.truthy(path:find("conditions%.json$"))
    end)
  end)

  describe("create", function()
    it("creates a condition and persists it", function()
      local c = summit.create("All tests pass")
      assert.is_not_nil(c)
      assert.equals("All tests pass", c.text)
      assert.equals("open", c.status)
      assert.is_string(c.id)
      assert.is_string(c.created_at)

      local all = summit.list()
      assert.equals(1, #all)
      assert.equals(c.id, all[1].id)
    end)
  end)

  describe("list", function()
    it("returns all conditions", function()
      summit.create("Condition 1")
      summit.create("Condition 2")
      local all = summit.list()
      assert.equals(2, #all)
    end)

    it("returns empty when none exist", function()
      local all = summit.list()
      assert.equals(0, #all)
    end)
  end)

  describe("get", function()
    it("returns condition by id", function()
      local created = summit.create("Find me")
      local found = summit.get(created.id)
      assert.is_not_nil(found)
      assert.equals("Find me", found.text)
    end)

    it("returns nil for bad id", function()
      assert.is_nil(summit.get("nonexistent"))
    end)
  end)

  describe("update", function()
    it("merges changes and updates timestamp", function()
      local created = summit.create("Original text")
      local updated = summit.update(created.id, { text = "Updated text" })
      assert.is_not_nil(updated)
      assert.equals("Updated text", updated.text)

      local fetched = summit.get(created.id)
      assert.equals("Updated text", fetched.text)
    end)

    it("returns nil for bad id", function()
      assert.is_nil(summit.update("nonexistent", { text = "nope" }))
    end)
  end)

  describe("delete", function()
    it("removes condition and returns true", function()
      local c = summit.create("Delete me")
      assert.is_true(summit.delete(c.id))
      assert.is_nil(summit.get(c.id))
      assert.equals(0, #summit.list())
    end)

    it("returns false for bad id", function()
      assert.is_false(summit.delete("nonexistent"))
    end)
  end)

  describe("set_status", function()
    it("transitions open to met", function()
      local c = summit.create("Meet me")
      local updated = summit.set_status(c.id, "met")
      assert.is_not_nil(updated)
      assert.equals("met", updated.status)

      local fetched = summit.get(c.id)
      assert.equals("met", fetched.status)
    end)

    it("transitions met to open", function()
      local c = summit.create("Reopen me")
      summit.set_status(c.id, "met")
      local updated = summit.set_status(c.id, "open")
      assert.is_not_nil(updated)
      assert.equals("open", updated.status)
    end)

    it("transitions open to abandoned", function()
      local c = summit.create("Abandon me")
      local updated = summit.set_status(c.id, "abandoned")
      assert.is_not_nil(updated)
      assert.equals("abandoned", updated.status)
    end)

    it("returns nil for invalid status", function()
      local c = summit.create("Bad status")
      local updated = summit.set_status(c.id, "invalid")
      assert.is_nil(updated)
    end)

    it("returns nil for nonexistent condition ID", function()
      local result = summit.set_status("nonexistent-id", "met")
      assert.is_nil(result)
    end)
  end)

  describe("hooks", function()
    it("dispatches condition.created hook", function()
      local received = nil
      hooks.on("condition.created", function(payload)
        received = payload
      end)

      local c = summit.create("Hook test")
      assert.is_not_nil(received)
      assert.equals(c.id, received.condition.id)
      assert.equals("Hook test", received.condition.text)
    end)

    it("dispatches condition.status_changed hook", function()
      local received = nil
      hooks.on("condition.status_changed", function(payload)
        received = payload
      end)

      local c = summit.create("Status hook")
      summit.set_status(c.id, "met")
      assert.is_not_nil(received)
      assert.equals("open", received.from)
      assert.equals("met", received.to)
      assert.equals(c.id, received.condition.id)
    end)

    it("dispatches condition.deleted hook", function()
      local received = nil
      hooks.on("condition.deleted", function(payload)
        received = payload
      end)

      local c = summit.create("Delete hook")
      summit.delete(c.id)
      assert.is_not_nil(received)
      assert.equals(c.id, received.condition_id)
    end)
  end)
end)
